version: '2'
services:
  php:
    restart: always
    container_name: atm_wallet
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8081:80'
    networks:
      container-net:
        ipv4_address: ${IPV4_ADDRESS}
    #network_mode: "host"
    build: ./images/php
networks:
  container-net:
    driver: bridge
    ipam:
      config:
      - subnet: ${IPV4_NETWORK}
        gateway: ${IPV4_GATEWAY}
